#ifndef INTERPOLATIONDECORATOR_GLOBAL_H
#define INTERPOLATIONDECORATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(INTERPOLATIONDECORATOR_LIBRARY)
#  define INTERPOLATIONDECORATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define INTERPOLATIONDECORATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // INTERPOLATIONDECORATOR_GLOBAL_H
