#ifndef GRIDSTATDECORATOR_GLOBAL_H
#define GRIDSTATDECORATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(GRIDSTATDECORATOR_LIBRARY)
#  define GRIDSTATDECORATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define GRIDSTATDECORATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // GRIDSTATDECORATOR_GLOBAL_H
