#ifndef STATICNODES_GLOBAL_H
#define STATICNODES_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(STATICNODES_LIBRARY)
#  define STATICNODESSHARED_EXPORT Q_DECL_EXPORT
#else
#  define STATICNODESSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // STATICNODES_GLOBAL_H
