#ifndef WIRELESSCOMMUNICATIONDECORATOR_GLOBAL_H
#define WIRELESSCOMMUNICATIONDECORATOR_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WIRELESSCOMMUNICATIONDECORATOR_LIBRARY)
#  define WIRELESSCOMMUNICATIONDECORATORSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WIRELESSCOMMUNICATIONDECORATORSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WIRELESSCOMMUNICATIONDECORATOR_GLOBAL_H
