#ifndef SHAPELOADER_GLOBAL_H
#define SHAPELOADER_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(SHAPELOADER_LIBRARY)
#  define SHAPELOADERSHARED_EXPORT Q_DECL_EXPORT
#else
#  define SHAPELOADERSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // SHAPELOADER_GLOBAL_H
